//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MyBlog.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class TBL_Comments
    {
        public int Comment_ID { get; set; }
        public int User_ID { get; set; }
        public System.DateTime Comment_Date { get; set; }
        public int Comment_Status { get; set; }
        public string Comment_Text { get; set; }
        public int Post_ID { get; set; }
    
        public virtual TBL_Users TBL_Users { get; set; }
        public virtual TBL_Posts TBL_Posts { get; set; }
    }
}
