//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MyBlog.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class TBL_Users
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public TBL_Users()
        {
            this.TBL_Comments = new HashSet<TBL_Comments>();
        }
    
        public int User_ID { get; set; }
        public string User_FullName { get; set; }
        public string User_UName { get; set; }
        public string User_PhoneNumber { get; set; }
        public string User_Email { get; set; }
        public string User_Image { get; set; }
        public string User_Password { get; set; }
        public Nullable<int> User_AddedBy { get; set; }
        public int User_Status { get; set; }
        public Nullable<System.DateTime> User_RegisterationDate { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<TBL_Comments> TBL_Comments { get; set; }
    }
}
